# World systems phases organize when certain systems should run

SETTLEMENT_UPDATE_PHASE = -100
CHARACTER_UPDATE_PHASE = -200
LATE_CHARACTER_UPDATE = -250
BUSINESS_UPDATE_PHASE = -300
CORE_SYSTEMS_PHASE = -1000
